# Generated by Django 5.1.3 on 2024-12-04 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_cliente_abogado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tarea', models.TextField()),
                ('fecha_tarea', models.DateField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='clients.cliente')),
            ],
            options={
                'ordering': ['fecha_tarea'],
            },
        ),
    ]
